name: main-website
on:
   workflow_dispatch:
   push:
      branches: [ "main" ]
   pull_request:
      branches: [ "main" ]
jobs:
   build:
      runs-on: ${{ matrix.os }}
      permissions:
         contents: write

      strategy:
         fail-fast: false
         matrix:
            os: [ ubuntu-24.04 ]
      
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          find .
      
      - name: Run script
        run: python src/script/generate_rss_feed_yaml.py

      - name: Construct index.md
        run: |
         python src/script/generate_index_header.py # >> index_header.md
         python src/script/generate_posts_list.py # >> index_posts.md
         cat index_header.md src/index_contents.md index_posts.md src/index_footer.md > src/index.md

      - name: Install Pandoc
        run: |
         sudo apt-get update
         sudo apt-get -y install --no-install-recommends pandoc
         pandoc --version

      - name: Generate HTML files
        run: |
         mkdir -p items
         pandoc -f markdown -t html --template=src/templates/index-template.html --eol=lf --toc --no-highlight -V pagetitle="index.html" src/index.md > index.html
         for file in src/items/*.md; do
            filename=$(basename -- $file)
            filename="${filename%.*}.html"

            cdate=`git log --diff-filter=A --format="%ci" -- $file`
            udate=`git log -1 --format="%ci" -- $file`
            export CREATED_DATE=${cdate:0:10}
            export UPDATED_DATE=${udate:0:10}

            pandoc -f markdown -t html --template=src/templates/template.html --lua-filter=src/filter/custom_meta_date.lua --lua-filter=src/filter/replace_dates.lua --preserve-tabs --eol=lf --toc --no-highlight -V pagetitle="$filename" --mathjax "$file" > "items/$filename"
         done
         for file in src/items/with-katex/*.md; do
            filename=$(basename -- $file)
            filename="${filename%.*}.html"

            cdate=`git log --diff-filter=A --format="%ci" -- $file`
            udate=`git log -1 --format="%ci" -- $file`
            export CREATED_DATE=${cdate:0:10}
            export UPDATED_DATE=${udate:0:10}

            pandoc -f markdown -t html5 --template=src/templates/template-with-katex.html --lua-filter=src/filter/custom_meta_date.lua --lua-filter=src/filter/replace_dates.lua --preserve-tabs --eol=lf --toc --no-highlight -V pagetitle="$filename" --mathjax "$file" > "items/$filename"
         done

      - name: Generate RSS feed
        run: |        
         pandoc feed.yaml -f markdown -t html --template ./src/rss/template.rss --metadata title="RSS feed for Amasaki Shinobu's Website" -o feed.rss

      - name: Copy image and style files
        run: |
         mkdir -p site/rss
         cp -r src/img site/img
         cp -r style site/style
         cp favicon.ico site/.
         cp feed.rss site/rss/.

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          exclude-paths: /src/templates /googlece7ee72c5edeb81f.html
          base-url-path: https://shinobuamasaki.github.io/

      - name: Copy index.html, items and sitemap.xml
        run: |
         cp index.html site/.
         cp -r items site/items
         cp sitemap.xml site/.
         cp googlece7ee72c5edeb81f.html site/.

      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
         branch: gh-pages
         folder: site
            
